artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rawatshubham09/Datascience_Class/raw/main/MachineLearning/Dataset/hypothyroid.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/hypothyroid.csv
  STATUS_FILE: artifacts/data_validation/status.txt